### PR TITLE
Switched to AsyncKeyedLock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@lukeskinner

**Comment by MarkCiliaVincenti** [comment]
@lukeskinner ?

**Comment by MarkCiliaVincenti** [comment]
@lukeskinner ?

**Comment by MarkCiliaVincenti** [comment]
@lukeskinner ?

**Comment by MarkCiliaVincenti** [comment]
@lukeskinner  are you interested or shall I close this PR?

**Comment by lukeskinner** [comment]
@MarkCiliaVincenti Thank you for taking the time to look into this change.

Unfortunately this project came to end with the start of the new V6 DKG a while ago. 
There aren't any more expected changes for this repository as there is no way to deploy them currently - I won't be able to take your change in this case.

The V6 DKG is completely different to this V5 (which this repository is built on) which mean this project became obsolete. 

I'm sorry about that. The replacement to this project is run by a different team at https://github.com/othub-io?tab=repositories

**Pull request closed without merging**
